CREATE TABLE usuarios
(
	ID VARCHAR2(36 CHAR) NOT NULL,
	NOME VARCHAR(256 CHAR) NOT NULL,
	SOBRENOME VARCHAR2(256 CHAR) NOT NULL,
	USUARIO VARCHAR2(32 CHAR) NOT NULL
);

ALTER TABLE usuarios
ADD CONSTRAINT usua_pk
PRIMARY KEY (ID);
