version: "3.2"

services:
  rabbitmq-server:
    build: ./rabbitmq
    container_name: rabbitmq-tutorial
    image: rabbitmq-tutorial
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq/data:/var/lib/rabbitmq:rw"
        # environment:
        # RABBITMQ_DEFAULT_USER: rabbitmq
        # RABBITMQ_DEFAULT_PASS: rabbitmq-is-awesome

