version: "3.3"

services:

  mysql:
    build:
      context: mysql/
    container_name: model-mapper-mysql
    image: mysql:8.0.17
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
