version: "3.3"

services:

  mysql:
    build:
      context: mysql/
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d