server:
  port: 8081
spring:
  application:
    name: spring-cloud-cloudfoundry
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: john
      password: 123
