spring:
  application:
    name: spring-eureka-feign-client
server:
  port: 8084
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    