# Configurações de criptografia.
criptografia:
  algoritmoCriptografia: DESede
  modoFeedback: CBC
  modoPreenchimento: PKCS5Padding
  chave: Oypn30NJfByzStoCmFf+/XAa4KTq6q7+
  
# Configurações do banco de dados onde são armazenadas as informações de execução do batch.
banco:
  batch:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: SPRING_BATCH
    senha: 5lHe55R56OHHS+sdSvEbow==
  programa:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE 
    username: SPRING_JOB_CONFIGURATION
    senha: Gs9H64msEr7GCyq6k0lYMwCLDGlAmhf/BoUXADK+evk=
    
# Configurações gerais do job.
meu-job:
  caminho-arquivo-de-usuarios: output/usuarios.csv
  total-de-registros: 40
  obter-clientes:
    tamanho-do-chunk: 10
  persistir-clientes:
    quantidade-de-leitores: 1
    tamanho-do-chunk: 10
  