server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: spring-reactor
      username: root
      password: spring-reactor-is-awesome