# Configurações gerais do job criador de usuários.
criador-usuarios:
  diretorio-arquivo-de-usuarios: output/
  total-de-registros: 5000
  fator-chance-lancamento-excecao: 0.05
  # Configurações de criptografia.
  criptografia:
    algoritmo-criptografia: DESede
    modo-feedback: CBC
    modo-preenchimento: PKCS5Padding
    chave: Oypn30NJfByzStoCmFf+/XAa4KTq6q7+
  aquisicao-usuarios:
    tamanho-do-lote: 500
  persistencia-usuarios:
    quantidade-de-processos: 4
    tamanho-do-lote: 100
  
spring:
  profiles:
    active:
    - "@profileAtivo@"
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    com.github.marceloleite2604.tutorials.spring.batch.job.configuration: DEBUG
    
