# Configurações do banco de dados MySQL.
banco:
  spring-batch:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch_db?useSSL=false&allowPublicKeyRetrieval=true
    username: spring_batch
    senha: 080CoY1pgozX7g1fQ9gkLw==
  programa:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/programa_db?useSSL=false&allowPublicKeyRetrieval=true
    username: programa
    senha: 5/0n9mDe6xcey5oQowUZuA==


