spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect

# Configurações do banco de dados Oracle.
criador-usuarios:
  banco:
    spring-batch:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:XE
      username: SPRING_BATCH
      senha-criptografada: 5lHe55R56OHHS+sdSvEbow==
    programa:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:XE 
      username: SPRING_JOB_CONFIGURATION
      senha-criptografada: Gs9H64msEr7GCyq6k0lYMwCLDGlAmhf/BoUXADK+evk=