spring:
  application:
    name: spring-batch-remote-chunking-worker
  activemq:
    broker-url: tcp://localhost:61616
    packages:
      trusted:
      - "org.springframework.batch"
      - "java.lang"
      - "java.util"
  jms:
    cache:
      enabled: false