version: "3.3"

services:

  mysql:
    container_name: spring-batch-mysql
    image: mysql:latest
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
