/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'marcelo' at '8/14/17 1:59 PM' with Gradle 3.2.1
 *
 * @author marcelo, @date 8/14/17 1:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
