spring:
  application:
    name: spring-security-database
    
programa:
  banco:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/programa_db?useSSL=false&allowPublicKeyRetrieval=true
    usuario: programa
    senha: programa
    quantidade-de-conexoes: 4